function [fitresult, gof] = createFit1(a, Y)
%CREATEFIT1(A,Y)
%  Create a fit.
%
%  Data for 'Renkin Equation' fit:
%      X Input : a
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Apr-2018 22:14:52
T = 20+273.15;
rho = 1.4;
mu = 0.01; 
Mw = [180 1200 17000 69000 150000];
a = ((3.*Mw)./(4.*pi.*rho.*(6.022.*10.^(23)))).^(1/3);
f = 6.*pi.*mu.*a;
Dgel = [4.5e-6 1.7e-6 4e-7 1e-7 1.3e-8];
Dwater = ((1.38065e-16)*T)./f;
Y = Dgel./Dwater;

%% Fit: 'Renkin Equation'.
[xData, yData] = prepareCurveData( a, Y );

% Set up fittype and options.
ft = fittype( '((1-(a/r))^2)*(1-(2.1*(a/r))+(2.09*(a/r)^3)-(0.95*(a/r)^5))', 'independent', 'a', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = 0;
opts.StartPoint = 0.957506835434298;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Renkin Equation' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'Y vs. a', 'Renkin Equation', 'Location', 'NorthEast' );
% Label axes
xlabel a
ylabel Y
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'Renkin Equation - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel a
ylabel Y
grid on


