function [fitresult, gof] = createFit1(h2, Ci)
%CREATEFIT1(H2,CI)
%  Create a fit.
%
%  Data for 'Ci(h2)' fit:
%      X Input : h2
%      Y Output: Ci
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Apr-2018 20:41:09

h2 = linspace(0.02,0.08,7);
Ci = [7.28e5 2.15e6 6.22e6 1.79e7 5.07e7 1.44e8 4.20e8];
%% Fit: 'Ci(h2)'.
[xData, yData] = prepareCurveData( h2, Ci );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [93545.6260911049 105.045261892001];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Ci(h2)' );
h = plot( fitresult, xData, yData );
legend( h, 'C_i vs. h_2', 'C_i(h_2)', 'Location', 'NorthEast' );
% Label axes
xlabel h_2
ylabel C_i
title('Initial Concentration vs. Tissue Depth');
grid on


